-- V12: widen t_tokens.token from varchar(255) to text.
--
-- JPA's default column length (255) was enough for the old HS256 access tokens (~229 chars,
-- 26 chars of headroom) but not for RS256: an RSA-2048 signature is 256 bytes -> 342 base64
-- chars for the signature segment alone, plus a larger header (kid claim), pushing the total
-- past 550 chars. Deploying RS256 without this migration makes every login fail with
-- "value too long for type character varying(255)" (see task-4b-brief.md).
--
-- The existing UNIQUE constraint (ukdjdnp60wf0lq8erni3suse1np on t_tokens.token) is preserved
-- by ALTER COLUMN ... TYPE text: Postgres does not drop constraints on a type-widening ALTER,
-- and a btree index entry of ~550 bytes is far under Postgres's ~2704-byte index-entry limit,
-- so no index change is needed here.
ALTER TABLE public.t_tokens ALTER COLUMN token TYPE text;
